### PR TITLE
Remove error logging

### LINKED ISSUE #67: DefaultHttpClient logs entire response on Error
In `DefaultHttpClient`, we allow clients to configure what level of logging they would like to have. This helps clients from leaking sensitive PII into their logs. 

However, if there is an HTTP error (non `200` code) when communicating with Smartsheet, then we log the entire response.

See the logging code below. We should not be using `REQUEST_RESPONSE` here.

```java
public void logRequest(HttpRequestBase request, HttpEntitySnapshot requestEntity,
                       HttpResponse response, HttpEntitySnapshot responseEntity, long durationMillis) throws IOException {
    logger.info("{} {}, Response Code:{}, Request completed in {} ms", request.getMethod(), request.getURI(),
            response.getStatusCode(), durationMillis);
    if (response.getStatusCode() != 200) {
        // log the request and response on error
        logger.warn(LOG_ARG, RequestAndResponseData.of(request, requestEntity, response, responseEntity, REQUEST_RESPONSE));
    } else {
        // log the summary request and response on success
        logger.debug(LOG_ARG, RequestAndResponseData.of(request, requestEntity, response, responseEntity, REQUEST_RESPONSE_SUMMARY));
    }
}
```

Asks:
- We shouldn't add additional logging for other 200-level response code. Ex a 201 should cause us to do WARN logging
- The client should be able to configure what we log on errors

### PR DESCRIPTION
**Pull request by zromano**
Fixes issue: https://github.com/smartsheet/smartsheet-java-sdk/issues/67

This will make it so we log the status on every request, but we do not log the response and request body and headers when there is an error.

The point of this is to prevent the logging of PII when there is a non 200 response.

### CODE REVIEW

File: src/main/java/com/smartsheet/api/internal/http/DefaultHttpClient.java [hunk 1]
```diff
@@ -156,13 +157,7 @@ public void logRequest(HttpRequestBase request, HttpEntitySnapshot requestEntity
 
         logger.info("{} {}, Response Code:{}, Request completed in {} ms", request.getMethod(), request.getURI(),
                 response.getStatusCode(), durationMillis);
-        if (response.getStatusCode() != 200) {
-            // log the request and response on error
-            logger.warn(LOG_ARG, RequestAndResponseData.of(request, requestEntity, response, responseEntity, REQUEST_RESPONSE));
```
Comment (zromano) [inline src/main/java/com/smartsheet/api/internal/http/DefaultHttpClient.java:161]: I just updated it so we don't log this at all on a non 200 response.

If they want more info, they can enable debug logging.

**Review by priyankalakhe — APPROVED** [review]
